### ISSUE TITLE
Placeholder for migrating all Kinesis Elasticsearch Sink issues to this repo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-elasticsearch-loader#1]
https://github.com/snowplow/snowplow/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22kinesis%20elasticsearch%20sink%22%20

Please copy the ticket descriptions and link back to the closed parent ticket for further reading.

**Comment by BenFradet** [comment]
done, closing

**Comment by alexanderdean** [comment]
Phew! Legend, thanks Ben.
