### ISSUE TITLE
Add support for Elasticsearch 5.x

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#10]
from snowplow/snowplow#3111:

>https://aws.amazon.com/about-aws/whats-new/2017/01/elasticsearch-5-now-available-on-amazon-elasticsearch-service/
~~We need a third build target to support this to be sure that there will be no complications.~~

**Comment by BenFradet** [comment]
@jbeemster @alexanderdean  https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients (especially the last paragraph) should we keep supporting transport?

**Comment by jbeemster** [comment]
Hey @BenFradet ... we only use the REST client at the moment.  However I think to remove the Transport Client entirely we should probably look at an RFC on Discourse as it is a pretty major change.

Am in favour of simplifying the application by moving to just REST however.

**Comment by alexanderdean** [comment]
I don't have a view on this - it looks like Transport is on the way out, but I'm unclear on when we should make the jump. Shall we create a ticket for it in 0.10.0 to start getting community discussion?

I think having this as a separate repo will help raise the profile of these kinds of questions too, which is a Good Thing.

**Comment by BenFradet** [comment]
To add to this, only the rest api is compatible across all major versions which means that if we want to support 5.x and the transport api we'll need to have 3 binaries (or we could cut down on the previous compats, ie stop support 1.x and/or 2.x).

**Comment by alexanderdean** [comment]
How about we keep Transport for this release but drop 1.x? So it's still two binaries and support for two ES versions, same as 0.8.0. This feels fairly conservative?

**Comment by BenFradet** [comment]
sgtm :+1:

**Comment by BenFradet** [comment]
Having thought about this more, wouldn't it make more sense to split http from tcp like what es does for their clients?

That would greatly reduce the size of the jars since they'd have complete different sets of deps as far as es is concerned.
And that would also greatly simplify the dependency mgmt (no src-compat).

As a result given the current plan, we'd have 3 artifacts:

- es-loader-http which would be fit for any es versions
- es-loader-tcp-2x
- es-loader-tcp-5x

what do you guys think?

**Comment by alexanderdean** [comment]
Oh that does make more sense... It also gives us a clearer path to sunsetting the Transport client?

**Comment by BenFradet** [comment]
yes we can just remove stuff as we go until we're only left with one artifact.

**Comment by kazjote** [comment]
We are very interested to have this feature available as soon as possible as we are currently migrating to Elasticsearch 5.5.1. Let me know if we can help somehow in research / development / testing.

**Comment by BenFradet** [comment]
@kazjote good to hear, are you using tcp or http?

**Comment by kazjote** [comment]
Both would work for us. However, http would be easier.
