### ISSUE TITLE
Remove Document Type

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-elasticsearch-loader#104]
It is getting deprecated in ES 7. We can leave it as a setting in final step and remove it from the rest code to minimize the impact

**Comment by BenFradet** [comment]
>We can leave it as a setting in final step and remove it from the rest code to minimize the impact

mmh if we're removing it from the code we should remove it from the configuration too

**Comment by szareiangm** [comment]
yes but how about the backward compatibility with older Elasticsearch clusters?

**Comment by BenFradet** [comment]
so let's keep it in :+1:

**Comment by szareiangm** [comment]
sure. let's keep it until we see how ES 7 client would be behave against older versions. cheers!

**Comment by BenFradet** [comment]
yup let's leave this open until we decide to actually make the change :+1:
