### ISSUE TITLE
Fix configuration not loading

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-elasticsearch-loader#113]
reported in #111

**Comment by amalow** [comment]
Hi there, I helped @jacobofarrell with #111, when trying to debug this I was noticing that args weren't being parsed through the StreamLoaderApp. This behaviour is consistent when running through `java -jar` and `sbt run`.

**Comment by szareiangm** [comment]
@amalow The reason is the `App` and the lazy loading. I have prepared the fix for this and will submit it today.
