### ISSUE TITLE
Update configuration example

### ISSUE THREAD

**Issue by razius** [snowplow/snowplow-elasticsearch-loader#116]
I see that the `nsq` and `kafka` keys were removed in 2725c3615d8d4eb0cf2da9402f3c69e1dacb66b0#diff-44ddfec53454989db60cd784f9fa0408 but it looks like the model wasn't updated with the correct keys:

https://github.com/snowplow/snowplow-elasticsearch-loader/blob/ab929ec5a7c9a5aabac9bba9d7814b03875934d0/core/src/main/scala/com.snowplowanalytics.stream/loader/model.scala#L34

https://github.com/snowplow/snowplow-elasticsearch-loader/blob/ab929ec5a7c9a5aabac9bba9d7814b03875934d0/core/src/main/scala/com.snowplowanalytics.stream/loader/model.scala#L41

```
configuration error: ConfigReaderFailures(KeyNotFound(nsq,Some(ConfigValueLocation(file:/config/config.hocon,1)),Set()),List(KeyNotFound(kinesis,Some(ConfigValueLocation(file:/config/config.hocon,1)),Set())))
```

**Comment by BenFradet** [comment]
Thanks for raising, feel free to open a PR :+1:

**Comment by szareiangm** [comment]
Can I ask someone please explain what is the issue please? The decision was not to have `nsq` and `kinesis` in the root of the yaml file and instead, we use either of them in `enabled`.
Like this sample for the old configuration yaml file:
```
kinesis {
  # Config for Kinesis
}
// and there could be nsq configuration but it was wrong to have both
nsq {
  # Config for Kinesis
}
```
that has changed in the new format:
```
queue {
  enabled = "kinesis"
  // and the configuration for the queue specified above
}
```
This change happened to have this component follow the same pattern like Enricher. 
I think you are using the old configuration file format and that is why you have that error. Could you please verify or elaborate so I can understand the issue and patch it?  @razius

**Comment by BenFradet** [comment]
ah I thought the configuration hadn't been updated to reflect the change you're talking about @szareiangm

**Comment by razius** [comment]
Aaah, I see. I'm using latest published version but I haven't noticed that the default branch is `develop`, not `master` so I was using the wrong config.
