### ISSUE TITLE
Allow AWS request signing for outbound events

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#12]
from snowplow/snowplow#3001:

>http://stackoverflow.com/questions/33760144/signing-aws-http-requests-with-apache-httpcomponents-client/33762950#comment68073867_33762950
https://github.com/inreachventures/aws-signing-request-interceptor

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http/src/main/scala/com/sksamuel/elastic4s/http/HttpClient.scala#L55

https://gist.github.com/alex1712/f41091ea316b6cdb0429dda71151a6d9

**Comment by nitin02** [comment]
Hi, when is the 0.9.0 release date?

**Comment by BenFradet** [comment]
We're currently working on it :+1:

**Comment by nitin02** [comment]
I've migrated to version 0.9.0. and I'm using SSL and AWS ES signing.

It works beautifully!
