### ISSUE TITLE
Trim long text fields

### ISSUE THREAD

**Issue by benjben** [snowplow/snowplow-elasticsearch-loader#152]
The maximum length of a text field in ES is 32766. When we try to insert a text longer than this, it fails with an error like this one :
```
failed with message Document contains at least one immense term in field="data.payload.enriched.contexts" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[123, 34, 115, 99, 104, 101, 109, 97, 34, 58, 34, 105, 103, 108, 117, 58, 99, 111, 109, 46, 115, 110, 111, 119, 112, 108, 111, 119, 97, 110]...', original message: bytes can be at most 32766 in length; got 40426
```

**Comment by chuwy** [comment]
There's problem with that particular field. If we trim it - we'll lose the actual data.

On the other hand, I _think_ we can turn it into an array of objects (like in a good sink) and then just trim every text field. In that case we won't loose any useful data as likely only natural language blobs will be trimmed.

**Comment by chuwy** [comment]
The big question is why `data.payload.enriched.contexts` is a text blob and not an array yet.

**Comment by chuwy** [comment]
`data.payload.enriched.contexts` is not an array because:

1. It goes from `EnrichedEvent` which stores `contexts` as string
2. If it was an array, ES would store it as array of `schema`/`data` pairs and `data` would have a lot of properties.

**Comment by benjben** [comment]
There are 2 distinct things:
- Not have our technology breakable, which is this issue
- Provide better functionality, which is #153 . Even is #153 I think that this issue still needs to be implemented

**Comment by benjben** [comment]
I tried to reproduce the issue and it turns out that ES can receive very very big text fields. The issue that we have is when we send a text to a field whose mapping is
```
{
  "type": "keyword",
  "index": true
}
```

**Comment by benjben** [comment]
Updating the mapping of such fields to
```
{
  "type": "text",
  "index": false
}
```
solves the issue.

It's important to keep in mind that such fields are not searchable.
