### ISSUE TITLE
Add custom endpoint overrides for Kinesis and DynamoDB

### ISSUE THREAD

**Issue by ZAYEC77** [snowplow/snowplow-elasticsearch-loader#157]
Hello 👋 

Is it possible to add `customEndpoint` property to config like it was added for Scala Stream Collector and for Scala Stream Enricher

https://github.com/snowplow/snowplow/blob/master/2-collectors/scala-stream-collector/examples/config.hocon.sample#L235
https://github.com/snowplow/snowplow/blob/master/3-enrich/stream-enrich/examples/config.hocon.sample#L69

Thanks

**Comment by jbeemster** [comment]
Hi @ZAYEC77 thanks for the PR - this is very timely as we are experimenting with localstack ourselves.  I have built an RC with this commit but in testing it seeing a few of these errors:

```
[main] ERROR com.amazonaws.services.kinesis.leases.impl.LeaseManager - Failed to get table status for es-loader-enriched
[main] ERROR com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Caught exception when initializing LeaseCoordinator
[main] INFO com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Initialization attempt 7
[main] INFO com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker - Initializing LeaseCoordinator
```

Trying to debug it now but if you have any ideas let me know!

**Comment by szareiangm** [comment]
I think this is the CBOR issue with Localstack. Please disable using environment variable it and it should work: https://github.com/mhart/kinesalite/issues/31

**Comment by jbeemster** [comment]
It was missing a setting: https://github.com/snowplow/snowplow-elasticsearch-loader/commit/ca619cd940a58968e3a066b76f1ddeea69ee251e

Working now!

Have also added disabling cloudwatch for a better local experience as well.

**Comment by ZAYEC77** [comment]
Great thanks for jumping into this issue so fast.
Honestly, it was my first PR with Scala code 😬 
I just tried to copy changes from Enricher code.
