### ISSUE TITLE
Add Postgres module

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-elasticsearch-loader#164]
We have been extended this component to send the data off to Postgres (JDBC compliant) database. We have added the `postgres` module beside `core` and `elasticsearch` to benefit from maintaining less code.

I know that there is `snowplow-rdb-loader` but that is not based on stream. Also, this way we could have one modular component to maintain and upgrade with less hassle if needed.

Also, this module can store the events in a sharded events table.

**Comment by chuwy** [comment]
Have a look at https://github.com/snowplow-incubator/snowplow-postgres-loader/tree/release/0.1.0, @szareiangm

**Comment by chuwy** [comment]
We have a dedicated loader now.
