### ISSUE TITLE
Migrate CHANGELOG from snowplow/snowplow

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-elasticsearch-loader#2]
* Use KES versions for the prior release titles, not Snowplow Rxx releases
* Remove the unnecessary "Kinesis Elasticsearch Sink: " prefixes
* Prefix the ticket numbers with snowplow/snowplow

Thus:

```
...

0.8.0 (2016-10-07)
------------------
Bump to 0.8.0 (snowplow/snowplow#2885)
Bump Scala Tracker to 0.3.0 (snowplow/snowplow#2899)
Allow parametrized timeouts for jest client (snowplow/snowplow#2897)
Does not take into account buffer configurations (snowplow/snowplow#2895)
Error messages are not helpful (snowplow/snowplow#2896)
Ensure field names do not contain any dots (snowplow/snowplow#2894)
Add support for Elasticsearch 2.x (snowplow/snowplow#2525)
Call Config.resolve() to resolve environment variables in hocon (snowplow/snowplow#2880)

...
```

**Comment by BenFradet** [comment]
Should this be part of the initial commit?

**Comment by alexanderdean** [comment]
What initial commit - we can preserve the git history from snowplow/snowplow...

**Comment by BenFradet** [comment]
and I thought that I was done with the grunt work :sob:

**Comment by BenFradet** [comment]
should the CHANGELOG be integrated into the commit history (might as well edit commit messages if so) or added in an ad hoc manner?

**Comment by alexanderdean** [comment]
I wouldn't integrate into the commit history, will take too long. Just add it as an additional commit in 0.9.0...
