### ISSUE TITLE
Change the log level of error log in bulk request's response

### ISSUE THREAD

**Issue by spenes** [snowplow/snowplow-elasticsearch-loader#207]
Currently, when bulk request's response contains error, we are including the failed record in error log. This makes the log volume size too big when the volume of failed requests is also big. Therefore, we should decrease the log level from `error` to something lower. Related line can be found [here](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/master/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L213).

**Comment by istreeter** [comment]
This was fixed by #226
