### ISSUE TITLE
Update to use Snowplow Scala Analytics SDK

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#21]
from snowplow/snowplow#2553:

>Use the JSON Event Transformer in there:
https://github.com/snowplow/snowplow-scala-analytics-sdk#21-json-event-transformer

**Comment by alexanderdean** [comment]
It would be great to get this one done. Moving our loaders to using an Analytics SDK is a super-important step in properly abstracting these loaders from snowplow/snowplow.
