### ISSUE TITLE
Improve use of Futures to avoid suspected deadlocks

### ISSUE THREAD

**Issue by istreeter** [snowplow/snowplow-elasticsearch-loader#238]
### Background

I have seen examples in production where the ES loader simply stops processing events, even though there is nothing obviously wrong.  I suspect it happens due to a deadlock involving Futures and a small thread pool.

There are places in the code where I believe we are mis-using Futures.  My suggestion is to address some of these antipatterns, in the hope that it fixes the deadlock problem.

Annoyingly I have not been able to pinpoint exactly where the deadlock happens.

### Justification for my suspicions

Currently we run all Futures on the global execution context.  The default parallelism for this execution context is equal to the number of processors.  On a small instance (e.g. t3.small) this means there are just two threads on which to execute all Futures.

Here are few of things which get run as tasks on the thread pool:

- Use the client to [index events in Elasticsearch](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L189)
- [Retry/backoff logic](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L135) to handle failures after indexing events.
- [Handle the result](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L168-L176) of indexing events.
- Use the client to [query the health of cluster](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L189)
- [Log the result](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L190-L199) of cluster health
- [Write failed events to kinesis](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/core/src/main/scala/com.snowplowanalytics.stream/loader/sinks/KinesisSink.scala#L85-L94)

Many of those tasks are started concurrently.  For example, when querying cluster health, we do not await the result of the future but we let it run in the background.  Same for sending failed events to kinesis; we do not await the result but let it run in the background. 
 So we could easily end up scheduling tasks simultaneously for the indexing task AND the cluster health task AND sending events to kinesis.

If we fill up the thread pool with tasks (especially blocking tasks) it is possible that we cannot execute any of the Future callbacks because there are no threads available, and then deadlock might happen.

The kinesis call in particular is wrapping a thread-blocking synchronous api call.  It is an antipattern to do this on the global execution context without wrapping it in `blocking {...}`.

### Suggested improvements

**Suggestion 1**. Await the result of [querying cluster health](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L188-L200) instead of letting the Future run in the background. This means we block the worker's main thread until we have the result of the health query.  It means we do not start sending failures to kinesis or indexing the next batch while this health query is ongoing.

**Suggestion 2.** Do not use a Future for sending failed events to kinesis.  Instead, the write to kinesis should happen synchronously on the main worker thread.

Suggestion 2 might be controversial because it might have a slight negative impact on the app's maximum throughput, when there are failed inserts. Alternative improvements in this area are to use a dedicated (non-global) execution context for the blocking kinesis client call, or wrap the blocking call in a `blocking {}` construct, so the global execution context can add an extra thread. However, I like my suggested fix because it forces KCL to only checkpoint the incoming kinesis events after the failures have been safely written to the output kinesis bad stream. And the alternative fixes have their own problems, like there's no backpressure mechanism if we can't sink events to kinesis fast enough, so we could blow up the app's memory when kinesis is unavailable.

**Suggestion 3**. Stop calling `response.result.status` on the health response, in case the response is an error response.  Currently this can raise an exception in the Future, which needs to be handled by the execution context.  I have no idea if this exception is problematic, but it cannot be helping.

**Comment by istreeter** [comment]
> All the Futures should be run on their dedicated thread pool.

Honestly, I don't think it's so clear cut.  The global context _is_ a dedicated thread pool, and it has some really nice features like respecting the `blocking {...}` construct by adding extra threads where needed.  It's even configurable at runtime using system properties.  I disagree with any hard-and-fast rule to never use it in production (although I acknowledge there are times to not use it).

I don't mind creating an explicit execution context backed by a fixed size pool.  It will mean we can be more explicit about the size of the pool, and we can pass it through the app.  But I don't believe just changing execution context will "fix" anything.

> If I understand correctly, you're saying that a callback is submitted as a new task to the thread pool, and is not part of the initial task, but the initial task doesn't complete (and thus doesn't release a slot on the thread pool) until the callback is executed ?

Yes to the first bit, no to the second bit.  Callbacks are submitted as new tasks on the thread pool.  But the initial task should complete immediately.

This is why I'm stuck pinpointing exactly how the deadlock can happen.  It might be something like one callback can't acquire a resource (e.g. the underlying elasticsearch client) because another callback is blocked from releasing it.  There's a lot of speculation here though.

> Do you prefer using blocking over Future because we need to wait for the completion of the sending to continue the processing (i.e. acking) ?

Yes.

Just to be clear though, the `blocking {...}` thing only makes sense inside a Future.  Typical usage is like this:

```scala
Future {
  blocking {
    client.putRecord()
  }
}
```

So my proposal is use neither `Future` nor `blocking`.  It will look simply like:

```scala
client.putRecord()
```

I will probably also batch the records when sending to kinesis, so at least we don't pay the penalty of waiting for `putRecord` to run multiple times in a row.

> Ideally we would put the acking in onComplete and use Futures everywhere, but I don't know if this is possible with the current design.

I would love to build a next generation elasticsearch loader that does everything asynchronously (like the new enrich).  But the current implementation is hard-wired to use the kinesis connectors framework, which requires that calls to `emit` and `fail` run synchronously.  The connectors framework knows nothing about Futures.  I think the mixture of Futures + synchronous framework is not helping us at the moment.

> > Await the result of [querying cluster health](https://github.com/snowplow/snowplow-elasticsearch-loader/blob/2.0.6/elasticsearch/src/main/scala/com/snowplowanalytics/stream/loader/clients/ElasticsearchBulkSender.scala#L188-L200) instead of letting the Future run in the background.
> 
> Then we should probably run that in blocking {} as well.

Actually this query does not block a thread of the execution context.  It is a well behaved non-blocking Future.  Because of how it is [implemented using a callback on a Promise](https://github.com/sksamuel/elastic4s/blob/v7.14.1/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/Executor.scala#L14-L24).  So I don't think we need `blocking {...}` for this one.

> Currently whatever the result of the health query we just log it but we don't act on it, so I don't see a reason to wait for it.

The reason for waiting is simply that I want to address this deadlock problem.  I agree it's annoying to deliberately wait for something when we don't need the result, but I am prepared to make this change if it improves the stability of the app.  By waiting, I can be confident we have released all resources (i.e. underlying elasticsearch client) before trying to re-use the elasticsearch client on the next batch.

**Comment by benjben** [comment]
That's very interesting !

So, if I try to sum things up, at the moment we have a mixture of blocking calls and `Future`s that are executed on the main (small) thread pool, and we suspect that there are some cases where it might end up in a deadlock.

The reason why we use `Future`s is that we have asynchronous tasks, and they should be treated differently than non-blocking tasks.

But the app is built on Kinesis connectors framework, which is all synchronous. I start to think that using `Future`s in this context does not make much sense, because we can't use callbacks, and using `await` would be quite close to not have `Future`s at all.

If we just get rid of all the `Future`s, it's also not nice because then we'll have a lot of blocking I/O tasks running on the main thread pool and we'll be wasting CPU.

So in this context, I think that our best option here, is to get rid of all the `Future`s and to put all the asynchronous tasks inside `blocking {}`. If I understand correctly the [documentation](https://scala-lang.org/api/3.x/scala/concurrent.html#blocking-fffff7d2), when we do that, all the blocking tasks will be executed in their own thread, while this happens the CPU will take care of other tasks, and then when the asynchronous task is complete, processing can continue. So we can have many tasks running concurrently.

If we are afraid that it could overwhelm Elasticsearch, we could implement kind of a pool to send requests to it.

WDYT ?
