### ISSUE TITLE
Automatic rotation of index names

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#24]
from snowplow/snowplow#1886:

>Please add an option to the kinesis-elasticsearch-sink so every day/week/month year can start with a new index. Like a logrotate.
Config example:
location {
index: "snowplow"
type: "enriched"
rotate: "day" (options: none/day/week/month/year)
}
The index name can be like this:
"snowplow_20150708" in case of rotate=day
"snowplow_2015_w13" in case of rotate=week
"snowplow_2015_m7" in case of rotate=month
"snowplow_2015" in case of rotate=year
"snowploy" in case of rotate=none (or not configured)

**Comment by BenFradet** [comment]
@alexanderdean should this be in my milestone?

**Comment by alexanderdean** [comment]
Where did we get to with this one @jbeemster (please re-read the parent thread)?

**Comment by alexanderdean** [comment]
No let's leave @BenFradet

**Comment by gincor** [comment]
In case anyone else was looking for this feature - here's how we made it work. The tagline here is #goodenough:

1) 
modify SnowplowElasticsearchTransformer.scala to this (or something similar) 

```
...
import java.util.Calendar
...
class SnowplowElasticsearchTransformer(documentIndex: String, documentType: String)
  extends ITransformer[ValidatedRecord, EmitterInput] with StdinTransformer {

  val now: Calendar = Calendar.getInstance()
  val currentYear: Int = now.get(Calendar.YEAR)
  val currentMonth: Int = now.get(Calendar.MONTH) + 1
  val currentDay: Int = now.get(Calendar.DAY_OF_MONTH)
  val currentSuffix: String = {
    "-%d.%02d.%02d".format(currentYear, currentMonth, currentDay)
  }

  /**
   * Convert an Amazon Kinesis record to a JSON string
   *
   * @param record Byte array representation of an enriched event string
   * @return ValidatedRecord for the event
   */
  override def toClass(record: Record): ValidatedRecord = {
    val recordString = new String(record.getData.array, UTF_8)
    (recordString, toJsonRecord(recordString))
  }

  /**
   * Convert a buffered event JSON to an EmitterInput
   *
   * @param record ValidatedRecord containing a good event JSON
   * @return An EmitterInput
   */
  override def fromClass(record: ValidatedRecord): EmitterInput =
    record.map(_.map(r => r.id match {
      case Some(id) => new ElasticsearchObject(documentIndex + currentSuffix, documentType, id, r.json)
      case None => new ElasticsearchObject(documentIndex + currentSuffix, documentType, r.json)
    }))
```

2) 
set a cronjob to restart the sink at midnight


Why do all this? In our case, we load our tracking events into a 'shared' elasticsearch cluster where all other indexes rotate daily and we want a unified way to dispose of old data. Yes, delete by query is not that horrible performancewise, but it's a hassle nevertheless. We don't really care that the index only uses day of loading, not some collector_tstamp or similar.

**Comment by alexanderdean** [comment]
Nudge @jbeemster. I'm not sure why a suffix has to be dynamically set in the Scala code - can't an Elasticsearch alias be used?

**Comment by jbeemster** [comment]
Hey @alexanderdean @gincor - the strategy we employ is to use an Elasticsearch Alias which we set in the configuration file for the Elasticsearch Sink.  

We then update the alias to point to new indices as required.  Writing some python / bash to create a new index and update the alias is fairly simply and does not require any need for customisation of the binary or rebooting the sink.

For more advanced management you can also look at tools like Curator:

> https://github.com/elastic/curator

**Comment by alexanderdean** [comment]
Thanks for clarifying that @jbeemster! I am closing this now as a won't fix.
