### ISSUE TITLE
Stop supporting the Transport API?

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#53]
As unveiled in https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients (towards the very end), the transport API is doomed to be deprecated.

As a result, we could envision stopping supporting in this project, what do people think?

**Comment by alexanderdean** [comment]
Scheduling for the next-but-one release to focus minds :-)

**Comment by szareiangm** [comment]
Can I remove them and refactor the code base a little?

No code and logic change, but mostly moving classes to packages and renaming classes to generalize names and be more descriptive of what they do? 
I promise to test the whole thing and not insist on my opinion.  I also would bump the libraries/sdk that are proposed in the other issues, too as a bonus 😄

**Comment by BenFradet** [comment]
I think we need to discuss this a bit further before we make the decision to drop the support API, wdyt @alexanderdean @jbeemster ?

**Comment by jbeemster** [comment]
We haven't used the Transport API in production for well over a year - I think we can quite comfortably stop supporting this API now.

**Comment by alexanderdean** [comment]
Fine by me

**Comment by szareiangm** [comment]
I will have PR soon for this next week. I need to finalize my changes. Basically, I bumped every library used including the Snowplow Scala tracker and restructured the code a bit.

Is this fine to bump Scala to 2.12 and SBT to 1.5?

**Comment by BenFradet** [comment]
>Is this fine to bump Scala to 2.12 and SBT to 1.5?

yes, however they should live in separate commits
