### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#56]
Using:

- BINTRAY_SNOWPLOW_GENERIC_USER
- BINTRAY_SNOWPLOW_GENERIC_API_KEY

We also need a new repo: `snowplow-elasticsearch-loader` in snowplow-generic

**Comment by jbeemster** [comment]
Hey @BenFradet - if this is pressing I can add those credentials for you and setup that repo for you.

**Comment by BenFradet** [comment]
I'm not done with the dev yet so I think we're good for now, I'll shout if it becomes a concern :+1: , thanks

**Comment by alexanderdean** [comment]
@BenFradet is there a reason not to just rename the existing package:

https://bintray.com/snowplow/snowplow-generic/snowplow-kinesis-elasticsearch-sink

I don't believe renaming the package will break any of the existing "legacy" download links...

**Comment by BenFradet** [comment]
@alexanderdean ah, cool then, let's rename it

**Comment by BenFradet** [comment]
@alexanderdean ping me when you renamed it :+1:

**Comment by alexanderdean** [comment]
Renamed, @BenFradet. /cc @jbeemster in case there are any unexpected CI/CD-like consequences

**Comment by BenFradet** [comment]
mmh still getting 400, I'll try tomorrow

**Comment by BenFradet** [comment]
Still getting 400s and the package still appears to exist with the old name: https://bintray.com/snowplow/snowplow-generic/snowplow-kinesis-elasticsearch-sink

**Comment by alexanderdean** [comment]
Whoops, butter fingers, try again now?

**Comment by BenFradet** [comment]
it worked 👍
