### ISSUE TITLE
Stop closing ElasticSearch clients when the Emitter is closed

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#67]
It seems that an issue occurs when resharding:

>java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED

Found an issue that fits ours: https://issues.apache.org/jira/browse/HTTPASYNC-104

**Comment by BenFradet** [comment]
During resharding emitters are closed, it seems the rest client doesn't survive being closed and causes the above issue.

**Comment by neerajjain92** [comment]
@BenFradet How to solve this?
