### ISSUE TITLE
Make Kinesis and NSQ config a coproduct

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow-elasticsearch-loader#68]
since they are mutually exclusive

**Comment by szareiangm** [comment]
should they be like Options in the setting config file and two modules in the project?
 The moduling in the project is based on the sink, not source. like tcp/http/etc

**Comment by BenFradet** [comment]
there should be something along the lines of:

```scala
sealed trait SourceConfig
final case class NsqConfig(...) extends SourceConfig
final case class KinesisConfig(...) extends SourceConfig
```

You can have a look at https://github.com/snowplow/snowplow/commit/42aad2d6a1fde6d52e1453ed1630ecc48472f706#diff-7cd83a9f81a7c59b0b6facd7ed5fc59a for inspiration.

By the way I just created https://gitter.im/snowplow/snowplow-elasticsearch-loader if you want to discuss further.

**Comment by szareiangm** [comment]
Will be in my PR next week.
