### ISSUE TITLE
[Question] What if you're using AWS ElasticSearch?

### ISSUE THREAD

**Issue by ktseytlin** [snowplow/snowplow-elasticsearch-loader#71]
The README in the Snowplow documentation refers to (some ElasticSearch config changes) [https://github.com/snowplow/snowplow/wiki/Elasticsearch-Loader-Setup]. However, if you're using  AWS's ElasticSearch you don't get access to modifying these different config values.

Additionally, AWS has (docs regarding moving data from AWS Kinesis to AWS ES)[http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-aws-integrations.html#es-aws-integrations-kinesis-lambda-es] which describe using a Lambda function instead.

What do y'all believe is the best approach to using AWS ElasticSearch service for the Snowplow ElasticSearch loader? Should I adjust the loader code in some specific manner? Should I build a Lambda function? Any other suggestions?

Thanks!

**Comment by alexanderdean** [comment]
Hi @ktseytlin - the ES Loader works fine with AWS Elasticsearch (that's almost exclusively how we use it). Please direct any support questions to our forums:

https://discourse.snowplowanalytics.com/
