### ISSUE TITLE
Sharded Indices by Date

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-elasticsearch-loader#82]
One common practice using Elasticsearch, is to have daily indices. I have this suggestion to have it in this project and I can write the codes for it:
- Having a new optional setting to select which timestamp field to use for sharding
- Having a new optional setting to have the index name suffix.

Also these settings are nice to have and we can add them:
- Number of shards and replicas per index
- Index mapping schema file path. Instead of applying per index manually, the client can create it automatically. 

There is one more issue: `clusterType` should be `documentType` to match Elasticsearch analogy.

**Comment by alexanderdean** [comment]
Assigning to @jbeemster for his view on this.

**Comment by jbeemster** [comment]
Hey @alexanderdean this seems like the same ticket as this?

> https://github.com/snowplow/snowplow-elasticsearch-loader/issues/24

Internally we manage all indices outside of the loader and by creating daily indexes which we push data into by leveraging the alias system within Elasticsearch - essentially:

1. Create new daily index with the same mapping as current daily index
2. Update alias to point to new index and drop pointer to old index
3. Update a secondary query alias which contains a pointer to all of the daily indexes for querying purposes

In short from the previous threads we have had on this topic I am not hugely in favour of adding the configuration and maintenance of mappings / indexes to the loader itself.  The sharding idea has also come up before and could be quite nice to be able to sort late arriving data into the correct index.  But the ability to alias all daily indexes together means that you can still query all of your data sorted by the timestamp you need and select exactly what you need regardless of if the data is "perfectly" sharded across your indexes.

Not sure the added complexity to the loader is worth it when such a simple workaround seems to do the trick - beyond simply making index management simpler out of the box are there other positives to having the data sharded very accurately from a data usability point of view?

**Comment by alexanderdean** [comment]
Makes sense @jbeemster, let's leave this open for further thoughts from the community.

**Comment by szareiangm** [comment]
Hello @jbeemster and pleasure to talk to you,

Elasticsearch has been evolved more aggressively, especially in the recent years. Using daily indices, helps to only run the queries only against the shards that we are interested using date math in the index name: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

Having your method, should we rerun the loader every day for a new index? what if we need a continues 247 loader to move forward everyday without manual intervention?

Besides, This would be an optional configuration. If someone doesn't need it, they won't use it. 

PS: Also, you can consider using this technique called Rollover in Elasticsearch instead of the curator: https://www.elastic.co/blog/managing-time-based-indices-efficiently
