### ISSUE TITLE
Abstract the core module

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-elasticsearch-loader#97]
There is a good chance that we could pull out all of Elasticsearch related codes from the `core` module and have it as abstract. After, we could move the Elasticsearch codes to its module and open up some room for other possible sinks for this project in future. 

What do you folks think?

**Comment by BenFradet** [comment]
:+1: from me, that's what we've been trying to do with stream enrich

**Comment by alexanderdean** [comment]
Exciting!
