### ISSUE TITLE
Generalize package name for the project

### ISSUE THREAD

**Issue by szareiangm** [snowplow/snowplow-elasticsearch-loader#98]
As for #97 we might want to generalize the package name for the project, too. So `com.snowplowanalytics.elasticsearch.loader` becomes `com.snowplowanalytics.stream.loader`.

- This naming be inline with `stream enrich` or `stream collector`
- Elasticsearch will be a module anyway and it will not be gone anywhere. we just remove a repetition.

**Comment by alexanderdean** [comment]
Prefer imperative over gerund for ticket names
